# fly.toml app configuration file generated for hahooks on 2024-02-07T14:51:40-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hahooks'
primary_region = 'bos'

[build]

# https://fly.io/docs/reference/configuration/#http_service-concurrency
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/up"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
